# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/palaashkolhe/1_PALAASH/UNIVERSITY OF WATERLOO/3B/SE 390/PeerToPeer"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/palaashkolhe/1_PALAASH/UNIVERSITY OF WATERLOO/3B/SE 390/PeerToPeer"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/palaashkolhe/1_PALAASH/UNIVERSITY OF WATERLOO/3B/SE 390/PeerToPeer/CMakeFiles" "/Users/palaashkolhe/1_PALAASH/UNIVERSITY OF WATERLOO/3B/SE 390/PeerToPeer//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/palaashkolhe/1_PALAASH/UNIVERSITY OF WATERLOO/3B/SE 390/PeerToPeer/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named provider

# Build rule for target.
provider: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 provider
.PHONY : provider

# fast build rule for target.
provider/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/build
.PHONY : provider/fast

#=============================================================================
# Target rules for targets named requester

# Build rule for target.
requester: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 requester
.PHONY : requester

# fast build rule for target.
requester/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/build
.PHONY : requester/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/main.cpp.s
.PHONY : main.cpp.s

src/Networking/client.o: src/Networking/client.cpp.o
.PHONY : src/Networking/client.o

# target to build an object file
src/Networking/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Networking/client.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Networking/client.cpp.o
.PHONY : src/Networking/client.cpp.o

src/Networking/client.i: src/Networking/client.cpp.i
.PHONY : src/Networking/client.i

# target to preprocess a source file
src/Networking/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Networking/client.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Networking/client.cpp.i
.PHONY : src/Networking/client.cpp.i

src/Networking/client.s: src/Networking/client.cpp.s
.PHONY : src/Networking/client.s

# target to generate assembly for a file
src/Networking/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Networking/client.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Networking/client.cpp.s
.PHONY : src/Networking/client.cpp.s

src/Networking/server.o: src/Networking/server.cpp.o
.PHONY : src/Networking/server.o

# target to build an object file
src/Networking/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Networking/server.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Networking/server.cpp.o
.PHONY : src/Networking/server.cpp.o

src/Networking/server.i: src/Networking/server.cpp.i
.PHONY : src/Networking/server.i

# target to preprocess a source file
src/Networking/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Networking/server.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Networking/server.cpp.i
.PHONY : src/Networking/server.cpp.i

src/Networking/server.s: src/Networking/server.cpp.s
.PHONY : src/Networking/server.s

# target to generate assembly for a file
src/Networking/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Networking/server.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Networking/server.cpp.s
.PHONY : src/Networking/server.cpp.s

src/Peers/bootstrap_node.o: src/Peers/bootstrap_node.cpp.o
.PHONY : src/Peers/bootstrap_node.o

# target to build an object file
src/Peers/bootstrap_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/bootstrap_node.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/bootstrap_node.cpp.o
.PHONY : src/Peers/bootstrap_node.cpp.o

src/Peers/bootstrap_node.i: src/Peers/bootstrap_node.cpp.i
.PHONY : src/Peers/bootstrap_node.i

# target to preprocess a source file
src/Peers/bootstrap_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/bootstrap_node.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/bootstrap_node.cpp.i
.PHONY : src/Peers/bootstrap_node.cpp.i

src/Peers/bootstrap_node.s: src/Peers/bootstrap_node.cpp.s
.PHONY : src/Peers/bootstrap_node.s

# target to generate assembly for a file
src/Peers/bootstrap_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/bootstrap_node.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/bootstrap_node.cpp.s
.PHONY : src/Peers/bootstrap_node.cpp.s

src/Peers/peer.o: src/Peers/peer.cpp.o
.PHONY : src/Peers/peer.o

# target to build an object file
src/Peers/peer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/peer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/peer.cpp.o
.PHONY : src/Peers/peer.cpp.o

src/Peers/peer.i: src/Peers/peer.cpp.i
.PHONY : src/Peers/peer.i

# target to preprocess a source file
src/Peers/peer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/peer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/peer.cpp.i
.PHONY : src/Peers/peer.cpp.i

src/Peers/peer.s: src/Peers/peer.cpp.s
.PHONY : src/Peers/peer.s

# target to generate assembly for a file
src/Peers/peer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/peer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/peer.cpp.s
.PHONY : src/Peers/peer.cpp.s

src/Peers/provider.o: src/Peers/provider.cpp.o
.PHONY : src/Peers/provider.o

# target to build an object file
src/Peers/provider.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/provider.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/provider.cpp.o
.PHONY : src/Peers/provider.cpp.o

src/Peers/provider.i: src/Peers/provider.cpp.i
.PHONY : src/Peers/provider.i

# target to preprocess a source file
src/Peers/provider.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/provider.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/provider.cpp.i
.PHONY : src/Peers/provider.cpp.i

src/Peers/provider.s: src/Peers/provider.cpp.s
.PHONY : src/Peers/provider.s

# target to generate assembly for a file
src/Peers/provider.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/provider.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/provider.cpp.s
.PHONY : src/Peers/provider.cpp.s

src/Peers/requester.o: src/Peers/requester.cpp.o
.PHONY : src/Peers/requester.o

# target to build an object file
src/Peers/requester.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/requester.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/requester.cpp.o
.PHONY : src/Peers/requester.cpp.o

src/Peers/requester.i: src/Peers/requester.cpp.i
.PHONY : src/Peers/requester.i

# target to preprocess a source file
src/Peers/requester.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/requester.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/requester.cpp.i
.PHONY : src/Peers/requester.cpp.i

src/Peers/requester.s: src/Peers/requester.cpp.s
.PHONY : src/Peers/requester.s

# target to generate assembly for a file
src/Peers/requester.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/Peers/requester.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/Peers/requester.cpp.s
.PHONY : src/Peers/requester.cpp.s

src/RequestResponse/discovery_structs.o: src/RequestResponse/discovery_structs.cpp.o
.PHONY : src/RequestResponse/discovery_structs.o

# target to build an object file
src/RequestResponse/discovery_structs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/discovery_structs.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/discovery_structs.cpp.o
.PHONY : src/RequestResponse/discovery_structs.cpp.o

src/RequestResponse/discovery_structs.i: src/RequestResponse/discovery_structs.cpp.i
.PHONY : src/RequestResponse/discovery_structs.i

# target to preprocess a source file
src/RequestResponse/discovery_structs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/discovery_structs.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/discovery_structs.cpp.i
.PHONY : src/RequestResponse/discovery_structs.cpp.i

src/RequestResponse/discovery_structs.s: src/RequestResponse/discovery_structs.cpp.s
.PHONY : src/RequestResponse/discovery_structs.s

# target to generate assembly for a file
src/RequestResponse/discovery_structs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/discovery_structs.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/discovery_structs.cpp.s
.PHONY : src/RequestResponse/discovery_structs.cpp.s

src/RequestResponse/message.o: src/RequestResponse/message.cpp.o
.PHONY : src/RequestResponse/message.o

# target to build an object file
src/RequestResponse/message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/message.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/message.cpp.o
.PHONY : src/RequestResponse/message.cpp.o

src/RequestResponse/message.i: src/RequestResponse/message.cpp.i
.PHONY : src/RequestResponse/message.i

# target to preprocess a source file
src/RequestResponse/message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/message.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/message.cpp.i
.PHONY : src/RequestResponse/message.cpp.i

src/RequestResponse/message.s: src/RequestResponse/message.cpp.s
.PHONY : src/RequestResponse/message.s

# target to generate assembly for a file
src/RequestResponse/message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/message.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/message.cpp.s
.PHONY : src/RequestResponse/message.cpp.s

src/RequestResponse/task_request.o: src/RequestResponse/task_request.cpp.o
.PHONY : src/RequestResponse/task_request.o

# target to build an object file
src/RequestResponse/task_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/task_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/task_request.cpp.o
.PHONY : src/RequestResponse/task_request.cpp.o

src/RequestResponse/task_request.i: src/RequestResponse/task_request.cpp.i
.PHONY : src/RequestResponse/task_request.i

# target to preprocess a source file
src/RequestResponse/task_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/task_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/task_request.cpp.i
.PHONY : src/RequestResponse/task_request.cpp.i

src/RequestResponse/task_request.s: src/RequestResponse/task_request.cpp.s
.PHONY : src/RequestResponse/task_request.s

# target to generate assembly for a file
src/RequestResponse/task_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/task_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/task_request.cpp.s
.PHONY : src/RequestResponse/task_request.cpp.s

src/RequestResponse/task_response.o: src/RequestResponse/task_response.cpp.o
.PHONY : src/RequestResponse/task_response.o

# target to build an object file
src/RequestResponse/task_response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/task_response.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/task_response.cpp.o
.PHONY : src/RequestResponse/task_response.cpp.o

src/RequestResponse/task_response.i: src/RequestResponse/task_response.cpp.i
.PHONY : src/RequestResponse/task_response.i

# target to preprocess a source file
src/RequestResponse/task_response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/task_response.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/task_response.cpp.i
.PHONY : src/RequestResponse/task_response.cpp.i

src/RequestResponse/task_response.s: src/RequestResponse/task_response.cpp.s
.PHONY : src/RequestResponse/task_response.s

# target to generate assembly for a file
src/RequestResponse/task_response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/RequestResponse/task_response.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/RequestResponse/task_response.cpp.s
.PHONY : src/RequestResponse/task_response.cpp.s

src/utility.o: src/utility.cpp.o
.PHONY : src/utility.o

# target to build an object file
src/utility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/utility.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/utility.cpp.o
.PHONY : src/utility.cpp.o

src/utility.i: src/utility.cpp.i
.PHONY : src/utility.i

# target to preprocess a source file
src/utility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/utility.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/utility.cpp.i
.PHONY : src/utility.cpp.i

src/utility.s: src/utility.cpp.s
.PHONY : src/utility.s

# target to generate assembly for a file
src/utility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/provider.dir/build.make CMakeFiles/provider.dir/src/utility.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/requester.dir/build.make CMakeFiles/requester.dir/src/utility.cpp.s
.PHONY : src/utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... provider"
	@echo "... requester"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Networking/client.o"
	@echo "... src/Networking/client.i"
	@echo "... src/Networking/client.s"
	@echo "... src/Networking/server.o"
	@echo "... src/Networking/server.i"
	@echo "... src/Networking/server.s"
	@echo "... src/Peers/bootstrap_node.o"
	@echo "... src/Peers/bootstrap_node.i"
	@echo "... src/Peers/bootstrap_node.s"
	@echo "... src/Peers/peer.o"
	@echo "... src/Peers/peer.i"
	@echo "... src/Peers/peer.s"
	@echo "... src/Peers/provider.o"
	@echo "... src/Peers/provider.i"
	@echo "... src/Peers/provider.s"
	@echo "... src/Peers/requester.o"
	@echo "... src/Peers/requester.i"
	@echo "... src/Peers/requester.s"
	@echo "... src/RequestResponse/discovery_structs.o"
	@echo "... src/RequestResponse/discovery_structs.i"
	@echo "... src/RequestResponse/discovery_structs.s"
	@echo "... src/RequestResponse/message.o"
	@echo "... src/RequestResponse/message.i"
	@echo "... src/RequestResponse/message.s"
	@echo "... src/RequestResponse/task_request.o"
	@echo "... src/RequestResponse/task_request.i"
	@echo "... src/RequestResponse/task_request.s"
	@echo "... src/RequestResponse/task_response.o"
	@echo "... src/RequestResponse/task_response.i"
	@echo "... src/RequestResponse/task_response.s"
	@echo "... src/utility.o"
	@echo "... src/utility.i"
	@echo "... src/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

